### ISSUE TITLE
Miniconda3-latest-Linux-x86_64.sh: 438: [[: not found

### ISSUE THREAD

**Issue by Marietto2008** [verm/freebsd-stable-diffusion#3]
Hello.

Right now I've been able to run stable diffusion if the userland of linux is the centos one. But if it is ubuntu,the situation changes,because it does not work anymore. Probably some little modifications are needed within some shell scripts.

I've understood one or one of the many reasons why your tutorial does not work with ubuntu as userland instead of centos7. This is what I'm trying to do. First of all,I have installed ubuntu following this tutorial :

https://forums.freebsd.org/threads/linuxulator-how-to-install-brave-linux-app-on-freebsd-13-0.78879/

and then I've started to follow your instructions and I've reached the point where you say to install miniconda3. This is what happens when I try to do the same as you on a fresh installation of FreeBSD :

```
# miniconda-installer.sh
/compat/linux/bin/sh: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

as the error says,it refers to /compat/linux,but I'm using /compat/ubuntu,so,I've thought to make some little modification inside the script,changing the word linux with the word ubuntu. Below you see what happens when I run the modified script :

```
Miniconda3 will now be installed into this location:
/home/marietto/miniconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/marietto/miniconda3] >>> 
PREFIX=/home/marietto/miniconda3
md5sum: -: No such file or directory
WARNING: md5sum mismatch of tar archive
expected: 81b26c617ffd9011dea96fd57c13e71b
     got: 
Unpacking payload ...
                                                                                                    
Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: done
Executing transaction: done
Miniconda3-latest-Linux-x86_64.sh: 438: [[: not found

Installing * environment...

Miniconda3-latest-Linux-x86_64.sh: 444: [[: not found

CondaFileIOError: '/home/marietto/miniconda3/pkgs/envs/*/env.txt'. [Errno 2] No such file or directory: '/home/marietto/miniconda3/pkgs/envs/*/env.txt
```

my knowledge of the shell scripting is too low to understand how to fix that error. But I presume that you can.

**Comment by verm** [comment]
Please keep questions to installations using packages solely from ports it is what I use I can't help with anything else.

**Comment by Marietto2008** [comment]
Man,if I make the installation of the linux-miniconda-installer from ports :

`# /usr/ports/sysutils/linux-miniconda-installer`

or from the packages :

`# pkg install linux-miniconda-installer`

it does not change anything,because it unpacks the same script called `miniconda-installer`

it is easy for you to check what's wrong inside of it. Let's look on your disk for that script,that's unpacked on :

`/usr/local/bin/miniconda-installer`

and let's change the word linux with the word ubuntu,since I've activated ubuntu and not linux. And you see the error when you run it. This error should be fixed if we want that your tutorial works even for `/compat/ubuntu`

**Comment by verm** [comment]
Again I only use packages from ports I can't help you with anything else.  This is meant to use packages from ports not anything else.  Please keep your questions limited to this.  Thank you.

**Comment by Marietto2008** [comment]
I don't like your irreproachable behavior. The script to modify is the same. It does not matter if it is installed from ports or from packages. The "error" is inside that script. It makes no difference the method you use to install it. Well,it's not a real error,some little changes are needed because it has been created having in mind `/compat/linux` and not `/compat/ubuntu`.

**Comment by Marietto2008** [comment]
This is what you wrote on your tutorial :

Install [miniconda](https://docs.conda.io/en/latest/miniconda.html) from **ports** using pkg to install Linux Conda.

`#` **pkg**` install linux-miniconda-installer`

you say that you can offer support only if I make the installation of the script using ports,but you have used packages (exactly like me). You seem confused. Ports aren't the same as packages. Ports can be installed with **"make ; make install"** ; packages with **pkg install**. Is this correct ?

**Comment by verm** [comment]
Hello I am closing this ticket.  I did make another update in relation to libGL.so.1 see ticket #4.  If you have any issues relating to ports-only installations please let me know.  Thanks!
